version: 2.1

jobs:
    run_test_py3:
        docker:
            - image: svalinn/pymoab-py3-18.04
        steps:
            - checkout #pull repo in the docker container
            - run:
                working_drectory: #/directory
            command: python -m pytest

    run_test_py2:
        docker:
            - image: svalinn/pymoab-py2-18.04
        steps:
            - checkout #pull repo in the docker container
            - run:
                working_drectory: #/directory
            command: python -m pytest

workflows:
    my_workflows:
        jobs:
            - run_test_py3
            - run_test_py2
