version: 2.1

jobs:
    install:
        docker:
            - image: svalinn/pymoab-py3-10.04
        steps:
            - checkout #pull repo in the docker container
            - run: pip install -e . --user
run_test:
        docker:
            - image: svalinn/pymoab-py3-10.04
        steps: 
            - checkout #pull repo in the docker container
            - run: pip install -e . --user 
            - run:
                working_drectory: #/directory
        command: pytest

workflows:
    my_workflows:
        jobs:
